project_id = "qdvmekqcouchyhwstnuh"

[functions.chat]
verify_jwt = false

[functions.generate-questions]
verify_jwt = false

[functions.parse-pdf]
verify_jwt = false

[functions.student-insights]
verify_jwt = false

[functions.generate-demo-data]
verify_jwt = false

[functions.approve-waitlist]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.seed-challenges]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-waitlist-email]
verify_jwt = false
